### Importação de Arquivos e Bibliotecas

In [1]:
import pandas as pd
import win32com.client as win32
import pathlib

In [2]:
emails = pd.read_excel(r'Bases de Dados\Emails.xlsx')
lojas = pd.read_csv(r'Bases de Dados\Lojas.csv', sep=';',encoding='latin1')
vendas = pd.read_excel(r'Bases de Dados\Vendas.xlsx')

In [6]:
for i in range(1,26):
    emails.iloc[i-1, 0]=f'Shopping {i}'
    emails.iloc[i-1, 1]=f'Gerente {i}'
    emails.iloc[i-1, 2]=f'shopping{i}@gmail.com'
emails.iloc[25, 2]='diretoria@gmail.com'
display(emails)

           Loja     Gerente                E-mail
0    Shopping 1   Gerente 1   shopping1@gmail.com
1    Shopping 2   Gerente 2   shopping2@gmail.com
2    Shopping 3   Gerente 3   shopping3@gmail.com
3    Shopping 4   Gerente 4   shopping4@gmail.com
4    Shopping 5   Gerente 5   shopping5@gmail.com
5    Shopping 6   Gerente 6   shopping6@gmail.com
6    Shopping 7   Gerente 7   shopping7@gmail.com
7    Shopping 8   Gerente 8   shopping8@gmail.com
8    Shopping 9   Gerente 9   shopping9@gmail.com
9   Shopping 10  Gerente 10  shopping10@gmail.com
10  Shopping 11  Gerente 11  shopping11@gmail.com
11  Shopping 12  Gerente 12  shopping12@gmail.com
12  Shopping 13  Gerente 13  shopping13@gmail.com
13  Shopping 14  Gerente 14  shopping14@gmail.com
14  Shopping 15  Gerente 15  shopping15@gmail.com
15  Shopping 16  Gerente 16  shopping16@gmail.com
16  Shopping 17  Gerente 17  shopping17@gmail.com
17  Shopping 18  Gerente 18  shopping18@gmail.com
18  Shopping 19  Gerente 19  shopping19@gmail.com
19  Shopping 20  Gerente 20  shopping20@gmail.com
20  Shopping 21  Gerente 21  shopping21@gmail.com
21  Shopping 22  Gerente 22  shopping22@gmail.com
22  Shopping 23  Gerente 23  shopping23@gmail.com
23  Shopping 24  Gerente 24  shopping24@gmail.com
24  Shopping 25  Gerente 25  shopping25@gmail.com
25    Diretoria   Diretoria   diretoria@gmail.com

In [8]:
for i in range(1,26):
    lojas.iloc[i-1, 1]=f'Shopping {i}'
    
display(lojas)

    ID Loja         Loja
0         1   Shopping 1
1         2   Shopping 2
2         3   Shopping 3
3         4   Shopping 4
4         5   Shopping 5
5         6   Shopping 6
6         7   Shopping 7
7         8   Shopping 8
8         9   Shopping 9
9        10  Shopping 10
10       11  Shopping 11
11       12  Shopping 12
12       13  Shopping 13
13       14  Shopping 14
14       15  Shopping 15
15       16  Shopping 16
16       17  Shopping 17
17       18  Shopping 18
18       19  Shopping 19
19       20  Shopping 20
20       21  Shopping 21
21       22  Shopping 22
22       23  Shopping 23
23       24  Shopping 24
24       25  Shopping 25

### Criação de tabela para cada loja e definição do dia do "Indicador"

In [9]:
#incluir nome da loja em vendas
vendas = vendas.merge(lojas, on='ID Loja')

In [10]:
# Transformar as lojas em variáveis com seus próprios dataframes
dicionario_lojas = {}
for loja in lojas['Loja']:
    dicionario_lojas[loja] = vendas.loc[vendas['Loja']==loja, :]
# Exemplos
display(dicionario_lojas['Shopping 1'])
display(dicionario_lojas['Shopping 20'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Shopping 1
1,1,2019-01-01,1,Camiseta,2,180,360,Shopping 1
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Shopping 1
3,21,2019-01-02,1,Camisa Gola V Listrado,2,116,232,Shopping 1
4,34,2019-01-02,1,Sapato Listrado,1,363,363,Shopping 1
...,...,...,...,...,...,...,...,...
3975,69899,2019-12-25,1,Sapato Xadrez,4,368,1472,Shopping 1
3976,69903,2019-12-25,1,Terno Liso,5,720,3600,Shopping 1
3977,69928,2019-12-25,1,Meia,1,30,30,Shopping 1
3978,69944,2019-12-25,1,Gorro Xadrez,5,85,425,Shopping 1
3979,69944,2019-12-25,1,Sapato Xadrez,2,368,736,Shopping 1

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
80860,56,2019-01-02,20,Gorro Linho,3,124,372,Shopping 20
80861,60,2019-01-02,20,Casaco Linho,3,299,897,Shopping 20
80862,60,2019-01-02,20,Polo Liso,5,137,685,Shopping 20
80863,67,2019-01-02,20,Polo Linho,3,176,528,Shopping 20
80864,101,2019-01-02,20,Cinto Listrado,2,214,428,Shopping 20
...,...,...,...,...,...,...,...,...
84935,69960,2019-12-25,20,Polo,2,130,260,Shopping 20
84936,69960,2019-12-25,20,Sapato Liso,1,368,368,Shopping 20
84937,69960,2019-12-25,20,Sapato Estampa,3,358,1074,Shopping 20
84938,69969,2019-12-25,20,Pulseira Liso,1,87,87,Shopping 20
84939,69969,2019-12-25,20,Camiseta Liso,2,187,374,Shopping 20

In [11]:
# Definir o dia mais recente(atual)
dia_indicador = vendas['Data'].max()
print(dia_indicador)
print('{}/{}'.format(dia_indicador.day, dia_indicador.month))

2019-12-26 00:00:00
26/12

### Salvando as planilhas na pasta de backup

In [12]:
#identificar se a pasta já existe

caminho_backup = pathlib.Path(r'Backup Arquivos Lojas')

arquivos_pasta_backup = caminho_backup.iterdir()
lista_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup]

for loja in dicionario_lojas:
    if loja not in lista_nomes_backup:
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()
    
    
    #salvar dentro da pasta
    nome_arquivo = '{}_{}_{}.xlsx'.format(dia_indicador.month, dia_indicador.day, loja)
    local_arquivo = caminho_backup / loja / nome_arquivo
    dicionario_lojas[loja].to_excel(local_arquivo)

### Cálculo dos indicadores e envio dos emails para os gerentes

In [16]:
#definição de metas

meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [17]:
for loja in dicionario_lojas:

    vendas_loja = dicionario_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

    #faturamento
    faturamento_ano = vendas_loja['Valor Final'].sum()
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()
    

    #diversidade de produtos
    qtde_produtos_ano = len(vendas_loja['Produto'].unique())
    qtde_produtos_dia = len(vendas_loja_dia['Produto'].unique())
   


    #ticket medio
    valor_venda = vendas_loja.groupby('Código Venda').sum()
    ticket_medio_ano = valor_venda['Valor Final'].mean()
   
    #ticket_medio_dia
    valor_venda_dia = vendas_loja_dia.groupby('Código Venda').sum()
    ticket_medio_dia = valor_venda_dia['Valor Final'].mean()
  
    
    
    # Configuração do email a ser enviado
    outlook = win32.Dispatch('outlook.application')

    nome = emails.loc[emails['Loja']==loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = emails.loc[emails['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'
    
    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if qtde_produtos_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if qtde_produtos_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'

    # Corpo do email em HTML
    mail.HTMLBody = f'''
    <p>Bom dia, {nome}</p>

    <p>O resultado de ontem <strong>({dia_indicador.day}/{dia_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>

    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Dia</th>
        <th>Meta Dia</th>
        <th>Cenário Dia</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_dia:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_dia}</td>
        <td style="text-align: center">{meta_qtdeprodutos_dia}</td>
        <td style="text-align: center"><font color="{cor_qtde_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_dia:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_dia}">◙</font></td>
      </tr>
    </table>
    <br>
    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Ano</th>
        <th>Meta Ano</th>
        <th>Cenário Ano</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_ano:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_ano}</td>
        <td style="text-align: center">{meta_qtdeprodutos_ano}</td>
        <td style="text-align: center"><font color="{cor_qtde_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_ano:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_ano}">◙</font></td>
      </tr>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>

    <p>Att., Andrei</p>
    '''

    # Anexos (arquivos das lojas)
    attachment  = pathlib.Path.cwd() / caminho_backup / loja / f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    print('E-mail do {} enviado'.format(loja))

E-mail do Shopping 1 enviado
E-mail do Shopping 2 enviado
E-mail do Shopping 3 enviado
E-mail do Shopping 4 enviado
E-mail do Shopping 5 enviado
E-mail do Shopping 6 enviado
E-mail do Shopping 7 enviado
E-mail do Shopping 8 enviado
E-mail do Shopping 9 enviado
E-mail do Shopping 10 enviado
E-mail do Shopping 11 enviado
E-mail do Shopping 12 enviado
E-mail do Shopping 13 enviado
E-mail do Shopping 14 enviado
E-mail do Shopping 15 enviado
E-mail do Shopping 16 enviado
E-mail do Shopping 17 enviado
E-mail do Shopping 18 enviado
E-mail do Shopping 19 enviado
E-mail do Shopping 20 enviado
E-mail do Shopping 21 enviado
E-mail do Shopping 22 enviado
E-mail do Shopping 23 enviado
E-mail do Shopping 24 enviado
E-mail do Shopping 25 enviado

### Criação de ranking para diretoria

In [18]:
faturamento_lojas = vendas.groupby('Loja')[['Loja', 'Valor Final']].sum()
faturamento_lojas_ano = faturamento_lojas.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_ano)

nome_arquivo = '{}_{}_Ranking Anual.xlsx'.format(dia_indicador.month, dia_indicador.day)
faturamento_lojas_ano.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_arquivo))


vendas_dia = vendas.loc[vendas['Data']==dia_indicador, :]
faturamento_lojas_dia = vendas_dia.groupby('Loja')[['Loja', 'Valor Final']].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_dia)

nome_arquivo = '{}_{}_Ranking Dia.xlsx'.format(dia_indicador.month, dia_indicador.day)
faturamento_lojas_dia.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_arquivo))

             Valor Final
Loja
Shopping 24      1762419
Shopping 19      1731167
Shopping 14      1726110
Shopping 7       1722766
Shopping 20      1721763
Shopping 15      1721120
Shopping 3       1711968
Shopping 11      1707122
Shopping 1       1699681
Shopping 9       1698430
Shopping 10      1682870
Shopping 23      1678225
Shopping 4       1674824
Shopping 17      1668921
Shopping 5       1663770
Shopping 25      1653103
Shopping 16      1649014
Shopping 21      1648111
Shopping 8       1646739
Shopping 6       1640486
Shopping 22      1635060
Shopping 13      1631630
Shopping 18      1624879
Shopping 2       1590441
Shopping 12      1586444

             Valor Final
Loja
Shopping 8          3950
Shopping 23         3400
Shopping 17         2651
Shopping 21         2391
Shopping 6          1582
Shopping 18         1366
Shopping 3          1259
Shopping 5          1207
Shopping 19          937
Shopping 14          676
Shopping 11          650
Shopping 10          485
Shopping 15          381
Shopping 9           368
Shopping 2           170
Shopping 22          118

### Envio de e-mail para diretoria

In [ ]:
# Configuração do e-mail a ser enviado
outlook = win32.Dispatch('outlook.application')

mail = outlook.CreateItem(0)
mail.To = emails.loc[emails['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {dia_indicador.day}/{dia_indicador.month}'
mail.Body = f'''
Prezados, bom dia

Melhor loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[0]} com Faturamento R${faturamento_lojas_dia.iloc[0, 0]:.2f}
Pior loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[-1]} com Faturamento R${faturamento_lojas_dia.iloc[-1, 0]:.2f}

Melhor loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[0]} com Faturamento R${faturamento_lojas_ano.iloc[0, 0]:.2f}
Pior loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[-1]} com Faturamento R${faturamento_lojas_ano.iloc[-1, 0]:.2f}

Segue em anexo os rankings do ano e do dia de todas as lojas.

Att.,
Andrei
'''

# Anexos:
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx'
mail.Attachments.Add(str(attachment))


mail.Send()
print('E-mail da Diretoria enviado')